CREATE DATABASE IF NOT EXISTS localbites CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE localbites;

CREATE TABLE IF NOT EXISTS dishes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  category VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dish_id INT NOT NULL,
  customer_name VARCHAR(100) NOT NULL,
  notes TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_dish FOREIGN KEY (dish_id) REFERENCES dishes(id)
);
